# Shared-library helpers: symbol visibility, rpath, and window-system deps.

set(FLUID_SHARED_CMAKE_DIR "${CMAKE_CURRENT_LIST_DIR}")

function(fluid_write_macho_exports out_var)
    file(READ "${CMAKE_CURRENT_SOURCE_DIR}/include/fluid/capi.h" _header)
    set(_symbols)
    string(REGEX MATCHALL "fluid_[A-Za-z0-9_]+[ \t]*\\(" _matches "${_header}")
    foreach(_match IN LISTS _matches)
        string(REGEX REPLACE "[ \t]*\\($" "" _name "${_match}")
        list(APPEND _symbols "_${_name}")
    endforeach()
    list(REMOVE_DUPLICATES _symbols)
    list(SORT _symbols)
    set(_path "${CMAKE_CURRENT_BINARY_DIR}/generated/fluid.exports")
    file(MAKE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/generated")
    string(REPLACE ";" "\n" _text "${_symbols}")
    file(WRITE "${_path}" "${_text}\n")
    set(${out_var} "${_path}" PARENT_SCOPE)
endfunction()

function(fluid_set_relocatable_rpath target)
    if(WIN32)
        return()
    endif()
    if(APPLE)
        set(_rpath "@loader_path")
        set_target_properties(${target} PROPERTIES MACOSX_RPATH ON INSTALL_NAME_DIR "@rpath")
    else()
        set(_rpath "$ORIGIN")
    endif()
    set_target_properties(${target} PROPERTIES BUILD_RPATH "${_rpath}" INSTALL_RPATH "${_rpath}")
endfunction()

function(fluid_link_windowing_deps target)
    if(WIN32)
        target_link_libraries(${target} PRIVATE gdi32)
        return()
    endif()
    if(APPLE)
        target_link_libraries(${target} PRIVATE "-framework Cocoa" "-framework IOKit"
            "-framework CoreFoundation")
        return()
    endif()
    find_package(Threads REQUIRED)
    target_link_libraries(${target} PRIVATE Threads::Threads)
    if(CMAKE_DL_LIBS)
        target_link_libraries(${target} PRIVATE ${CMAKE_DL_LIBS})
    endif()
    find_library(FLUID_LIBRT rt)
    if(FLUID_LIBRT)
        target_link_libraries(${target} PRIVATE ${FLUID_LIBRT})
    endif()
    find_library(FLUID_LIBM m)
    if(FLUID_LIBM)
        target_link_libraries(${target} PRIVATE ${FLUID_LIBM})
    endif()
    if(GLFW_BUILD_X11)
        find_package(X11)
        if(X11_FOUND)
            target_link_libraries(${target} PRIVATE ${X11_LIBRARIES})
            foreach(_ext Xrandr Xinerama Xcursor Xi Xext)
                if(X11_${_ext}_LIB)
                    target_link_libraries(${target} PRIVATE ${X11_${_ext}_LIB})
                endif()
            endforeach()
        endif()
    endif()
    if(GLFW_BUILD_WAYLAND)
        find_package(PkgConfig QUIET)
        if(PKG_CONFIG_FOUND)
            pkg_check_modules(FluidWayland QUIET IMPORTED_TARGET wayland-client wayland-cursor
                wayland-egl xkbcommon)
            if(TARGET PkgConfig::FluidWayland)
                target_link_libraries(${target} PRIVATE PkgConfig::FluidWayland)
            endif()
        endif()
    endif()
endfunction()

function(fluid_configure_c_shared target)
    target_compile_definitions(${target} PRIVATE FLUID_BUILDING_SHARED)
    target_compile_definitions(${target} PUBLIC FLUID_SHARED)
    set_target_properties(${target} PROPERTIES
        OUTPUT_NAME fluid
        VERSION ${PROJECT_VERSION}
        SOVERSION ${PROJECT_VERSION_MAJOR}
        C_VISIBILITY_PRESET hidden
        CXX_VISIBILITY_PRESET hidden
        VISIBILITY_INLINES_HIDDEN ON
        WINDOWS_EXPORT_ALL_SYMBOLS OFF)
    if(WIN32)
        set_target_properties(${target} PROPERTIES PREFIX "")
    endif()
    fluid_set_relocatable_rpath(${target})
    fluid_link_windowing_deps(${target})
    if(APPLE)
        fluid_write_macho_exports(_exports)
        target_link_options(${target} PRIVATE "LINKER:-exported_symbols_list,${_exports}")
        set_property(TARGET ${target} APPEND PROPERTY LINK_DEPENDS "${_exports}")
    elseif(NOT MSVC)
        set(_map "${FLUID_SHARED_CMAKE_DIR}/fluid.version.map")
        target_link_options(${target} PRIVATE "LINKER:--version-script=${_map}")
        set_property(TARGET ${target} APPEND PROPERTY LINK_DEPENDS "${_map}")
        if(MINGW)
            target_link_options(${target} PRIVATE "LINKER:--exclude-libs,ALL")
        endif()
    endif()
endfunction()
